### ISSUE TITLE
Download parcel and install on one of the machine

### ISSUE THREAD

**Issue by arvind75** [arvind75/SEBC#1]
Src file /opt/cloudera/parcels/.flood/CDH-5.7.0-1.cdh5.7.0.p0.45-el6.parcel/CDH-5.7.0-1.cdh5.7.0.p0.45-el6.parcel does not exist - ip-172-31-3-236.us-west-2.compute.internal

Its seems that there was lack of space on the root FS on one of the node. It worked fine after cleaning up space...

**Comment by mfernest** [comment]
Please be sure to create an Issue for Installation. This comment would make more sense (to me) as part of the flow of your lab work, rather than a standalone issue with no context.
